### PR TITLE
Draw consistent background clip path for middle tabs

### PR DESCRIPTION
**Pull request by vcoolish**
This is needed to avoid color contrast problems for MIUI devices

### CODE REVIEW

**Comment by addisonElliott** [comment]
Hm, it's interesting that it's required for MIUI devices. Is this a bug?

Can you provide pictures of what sort of color contrast problems you're experiencing?

**Comment by vcoolish** [comment]
> Hm, it's interesting that it's required for MIUI devices. Is this a bug?
> 
> Can you provide pictures of what sort of color contrast problems you're experiencing?

It's not a bug. MIUI has a feature that makes layout force darker. But when we change the rect it doesn't happen.
So it comes out that left and right tabs remain with unchanged color and middle ones are with different colors. It looks very ugly and it's just a workaround to make the colors consistent.

before|after
-|-
IMAGE 2021-01-06 13:51:11|IMAGE 2021-01-06 13:51:16

**Comment by vcoolish** [comment]
Hi @addisonElliott 
Any updates on this?

**Comment by addisonElliott** [comment]
Sorry, I've been meaning to spend some time on this. I'll go ahead and merge it now, but it may be a day or two until I can release another version.

Thanks for being patient.

**Comment by vcoolish** [comment]
Thank you @addisonElliott :)

> Sorry, I've been meaning to spend some time on this. I'll go ahead and merge it now, but it may be a day or two until I can release another version.
> 
> Thanks for being patient.

**Pull request merged**
